spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: task-api-service

  datasource:
    url: jdbc:postgresql://localhost:5431/chronotaskdb
    username: chronouser
    password: chronopass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
